FROM python:3.12

WORKDIR /microservice5

RUN apt-get update && apt-get install -y \
    build-essential \
    libpq-dev \
    protobuf-compiler \
    && rm -rf /var/lib/apt/lists/*

RUN wget -q https://raw.githubusercontent.com/dapr/cli/master/install/install.sh -O - | /bin/bash

RUN pip install poetry 

COPY . /microservice5/

RUN poetry config virtualenvs.create false

RUN poetry install

EXPOSE 8007

CMD ["poetry", "run", "uvicorn", "service5.main:app", "--host", "0.0.0.0", "--port","8007", "--reload"]