_format_version: "3.0"
_transform: true

services:
  - name: user-service
    url: http://host.docker.internal:8003
  
  - name: product-service
    url: http://host.docker.internal:8004
    
  - name: order-service
    url: http://host.docker.internal:8005

  - name: inventory-service
    url: http://host.docker.internal:8006

  - name: payment-service
    url: http://host.docker.internal:8008

routes:
  - name: user-service-route
    service: user-service
    paths:
      - /user
    methods:
      - GET
      - POST
      - PATCH
      - DELETE

  - name: product-service-route
    service: product-service
    paths:
      - /product
    methods:
      - GET
      - POST
      - PATCH
      - DELETE

  - name: order-service-route
    service: order-service
    paths:
      - /order
    methods: 
      - GET
      - POST
      - PATCH
      - DELETE

  - name: inventory-service-route
    service: inventory-service
    paths:
      - /inventory
    methods: 
      - GET
      - POST
      - PATCH
      - DELETE

  - name: payment-service-route
    service: payment-service
    paths:
      - /payment
    methods: 
      - GET
      - POST
      - PATCH
      - DELETE