apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: userservice
spec:
  type: pubsub.kafka
  version: v1
  metadata:
  - name: brokers
    value: "daprkafkabroker.servicebus.windows.net:9093"  # The internal Kafka broker address
  - name: consumerGroup
    value: "user_service_group"  # Name of the consumer group
  - name: topics
    value: "user_service"
  - name: authRequired
    value: "false"  # Set to true if you have authentication
  - name: disableTls
    value: "true"  # Disable TLS if not using SSL
scopes:
- userservice